# SPDX-FileCopyrightText: 2021 The NGI Pointer Secure-Scuttlebutt Team of 2020/2021
#
# SPDX-License-Identifier: CC0-1.0

before:
  hooks:
    - go mod tidy
    # refreshes the tailwind css
    - go generate ./...

builds:
  - env:
      # needed for sqlite
      - CGO_ENABLED=1
    main: ./cmd/insert-user
    binary: go-ssb-room-insert-user
    goos:
      - linux
    goarch:
      - amd64
  - env:
      # needed for sqlite
      - CGO_ENABLED=1
    main: ./cmd/server
    binary: go-ssb-room
    goos:
      - linux
    goarch:
      - amd64

gomod:
  # sum.golang.org somehow doesn't handle replace as expected. TODO: file issue
  proxy: false
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

# for .deb packages
# see: https://goreleaser.com/customization/nfpm/
nfpms:
 - id: go-ssb-room
   package_name: go-ssb-room
   replacements:
     linux: Linux
     amd64: x86_64
   vendor: Secure-Scuttlebutt Community
   maintainer: Go-SSB-Room NGI-Pointer Team <go-ssb-room@ssb-ngi-pointer.email>
   homepage: https://scuttlebutt.nz
   description: SSB Room v2 server, written in Go
   license: MIT
   formats:
     - deb
   suggests:
     - ngingx
     - certbot
   empty_folders:
     - /var/log/go-ssb-room
   contents:
     - src: docs/files/example-systemd.service
       dst: /etc/systemd/system/go-ssb-room.service
       type: "config|noreplace"

     - src: docs/files/example-nginx.conf
       dst: /usr/share/go-ssb-room/nginx-example.conf

     # TODO: maybe (automatically) turn docs/README.md into a .txt with the links at the bottom?
     - src: README.md
       dst: /usr/share/go-ssb-room/README.md

     # TODO: add more docs we want?
   scripts:
     postinstall: docs/files/debian-postinstall.sh
     preremove: docs/files/debian-preremove.sh

archives:
  - replacements:
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
