# SPDX-FileCopyrightText: 2021 The NGI Pointer Secure-Scuttlebutt Team of 2020/2021
#
# SPDX-License-Identifier: CC0-1.0

[sqlite3]
# go test in the roomdb/sqlite package will create this
dbname = "testrun/TestSchema/roomdb"
blacklist = ["gorp_migrations"]

# marshal pub_key strings ala @asdjjasd as feed references.
[[types]]
  [types.match]
    type = "string"
    #tables = ['fallback_auth']
    name = "pub_key"
    nullable = false

  [types.replace]
    type = "roomdb.DBFeedRef"

  [types.imports]
    third_party = ['"github.com/ssbc/go-ssb-room/v2/roomdb"']

# convert from database-stored integers to the type roomdb.RoomConfig
[[types]]
  [types.match]
    name = "privacyMode"
    tables = ['config']
    type = "int64"
    nullable = false

  [types.replace]
    type = "roomdb.PrivacyMode"

  [types.imports]
    third_party = ['"github.com/ssbc/go-ssb-room/v2/roomdb"']
